name: nf-benchmark CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_demo:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.1-edge']
        paramPipeline: [--pipeline tcoffee]
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline as a demo with tcoffee as the pipeline and balibase as the benchmarker
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{matrix.paramPipeline}}

  test_regressive_alignment:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.1-edge']
        paramPipeline: ['--pipeline regressive_alignment --regressive_align true --align_methods CLUSTALO --skip_benchmark']
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Runs regressive_alignment pipeline on test mode
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{matrix.paramPipeline}} -profile test,docker

  Test t-coffee demo module
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, '[ci skip]')"
      strategy:
        matrix:
          # Nextflow versions: check pipeline minimum and current latest
          nxf_ver: ['20.04.1-edge']
      steps:
        # Check out the repository
        - uses: actions/checkout@v2
        - name: Checkout submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule sync --recursive
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        - name: Install Nextflow
          run: |
            wget -qO- get.nextflow.io | bash
            sudo mv nextflow /usr/local/bin/
        - name: Runs tcoffee pipeline as an application script on test mode
          run: |
            cd modules/pipelines/test_paired/tcoffee/
            nextflow run . -profile test,docker